baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pickup Position "Database"'
[[module.imports]]
path = 'github.com/gethinode/hinode'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
